FROM openjdk:8

LABEL application="Chronocorpus"
LABEL description="Client - Workers"
LABEL organiztation="NLP Tools for Polish from G4.19 Group - Wroclaw University of Science and Technology"
LABEL maintainer="tomasz.walkowiak@pwr.edu.pl"

RUN apt-get update
RUN apt-get install -y subversion maven

WORKDIR /home/install
COPY  ./pom.xml /home/install/pom.xml
COPY  ./computation-service /home/install/computation-service
WORKDIR /home/install/computation-service
RUN mvn  clean
RUN mvn  install



