version: '3.7'
services:
  base:
    image: chronocorpus
    build:
        context:  ./
        dockerfile: Dockerfile_computation-service
  chronopress:    
    container_name: chrono-chronopress
    build: ./chronopress
    depends_on:
      - base
    volumes:
        - ./chronopress/config.ini:/home/worker/config.ini
        - ./chronopress/chronopress:/home/worker/ccl    
        - ./chronopress/data:/home/worker/data
    working_dir: /home/worker/    
    entrypoint:
         - java
         - -Xms4g 
         - -Xmx24g  
         - -jar 
         - chronocorpus.jar
    restart: always
  monco:
    container_name: chrono-monco
    build: ./monco
    depends_on:
      - base
    volumes:
        - ./monco/config.ini:/home/worker/config.ini
        - ./monco/chronopress:/home/worker/ccl
        - ./monco/data:/home/worker/data
    working_dir: /home/worker/
    entrypoint:
         - java
         - -Xms4g
         - -Xmx24g
         - -jar
         - chronocorpus.jar
    restart: always
  climate:
    container_name: chrono-climate
    build: ./climate
    depends_on:
      - base
    volumes:
      - ./climate/config.ini:/home/worker/config.ini
      - ./climate/climate:/home/worker/ccl
      - ./climate/data:/home/worker/data
    working_dir: /home/worker/
    entrypoint:
      - java
      - -Xms2g
      - -Xmx14g
      - -jar
      - chronocorpus.jar
    restart: always
  rest:
    container_name: chrono-rest
    build:
        context:  ./
        dockerfile: Dockerfile_rest-service
    ports:
        - "8080:8080"
    volumes:
        - ./rest-service/config.ini:/home/worker/config.ini
    working_dir: /home/worker/    
    depends_on:
      - base
    entrypoint:
         - java
         - -jar 
         - RESTchronocorpus.jar       
    restart: always
    
  frontend: 
    container_name: chrono-frontend
    build: ./frontend
    ports:
        - "80:80"
    restart: always        
