FROM maven:3.8.1-openjdk-17-slim as builder

LABEL application="Chronocorpus"
LABEL description="Client - Workers"
LABEL organiztation="NLP Tools for Polish from G4.19 Group - Wroclaw University of Science and Technology"
LABEL maintainer="tomasz.walkowiak@pwr.edu.pl"

WORKDIR /home/install
COPY  ./pom.xml /home/install/pom.xml

COPY  ./rest-service /home/install/rest-service
WORKDIR /home/install/rest-service
RUN mvn -U clean install

FROM openjdk:17
 
WORKDIR /home/worker
COPY --from=builder /home/install/rest-service/target/RESTchronocorpus.jar .

