##############################################
#  NLP Tools for Polish from G4.19 Group
#  Wroclaw University of Science and Technology
#  
#  Client - Workers
#           chrono...
#
#  Contact: Tomasz.Walkowiak@pwr.edu.pl
#
###############################################

FROM openjdk:8 as builder

LABEL application="Chronocorpus"
LABEL description="Client - Workers"
LABEL organiztation="NLP Tools for Polish from G4.19 Group - Wroclaw University of Science and Technology"
LABEL maintainer="tomasz.walkowiak@pwr.edu.pl"

RUN apt-get update
RUN apt-get install -y subversion maven

WORKDIR /home/install
COPY  ./pom.xml /home/install/pom.xml

COPY  ./rest-service /home/install/rest-service
WORKDIR /home/install/rest-service
RUN mvn clean
RUN mvn install

FROM openjdk:8
 
WORKDIR /home/worker
COPY --from=builder /home/install/rest-service/target/RESTchronocorpus.jar .

