version: '3.3'
services:
  base:
    image: chronocorpus-monco
    build:
        context:  ./
        dockerfile: Dockerfile_computation-service
  chronopress:    
    container_name: chrono-chronopress-monco
    build: ./chronopress
    depends_on:
      - base
    volumes:
        - ./chronopress/config.ini:/home/worker/config.ini
        - ./chronopress/chronopress:/home/worker/ccl    
        - ./chronopress/data:/home/worker/data
    working_dir: /home/worker/    
    entrypoint:
         - java
         - -Xms4g 
         - -Xmx24g  
         - -jar 
         - chronocorpus.jar
    restart: always
    
         
  rest:
    container_name: chrono-rest-monco
    build:
        context:  ./
        dockerfile: Dockerfile_rest-service
    ports:
        - "8081:8080"
    volumes:
        - ./rest-service/config.ini:/home/worker/config.ini
    working_dir: /home/worker/    
    depends_on:
      - base
    entrypoint:
         - java
         - -jar 
         - RESTchronocorpus.jar       
    restart: always
    
  frontend: 
    container_name: chrono-frontend-monco
    build: ./frontend
    ports:
        - "8082:80"
        