FROM maven:3.8.1-openjdk-17-slim

LABEL application="Chronocorpus"
LABEL description="Client - Workers"
LABEL organiztation="NLP Tools for Polish from G4.19 Group - Wroclaw University of Science and Technology"
LABEL maintainer="tomasz.walkowiak@pwr.edu.pl"

WORKDIR /home/install
COPY  ./pom.xml /home/install/pom.xml
COPY  ./computation-service /home/install/computation-service
WORKDIR /home/install/computation-service
RUN mvn -U clean install




